import {
  SiGmail,
  SiKubernetes,
  SiTypescript,
  SiAzuredevops,
  SiTerraform,
  SiDocker,
  SiGrafana,
  SiSonarqube,
  SiAqua,
  SiAzurepipelines,
  SiAzurefunctions,
  SiMicrosoftazure,
  SiPrometheus,
  SiAwslambda,
  SiAmazons3,
  SiAmazonec2,
  SiAmazonecs,
  SiAmazoneks,
  SiArgo,
  SiGithub,
  SiLinkedin,
  SiInstagram,
  SiX,
  SiFacebook,
} from "@icons-pack/react-simple-icons";

const ICON_MAP: Record<string, any> = {
  SiGmail,
  SiKubernetes,
  SiTypescript,
  SiAzuredevops,
  SiTerraform,
  SiDocker,
  SiGrafana,
  SiSonarqube,
  SiAqua,
  SiAzurepipelines,
  SiAzurefunctions,
  SiMicrosoftazure,
  SiPrometheus,
  SiAwslambda,
  SiAmazons3,
  SiAmazonec2,
  SiAmazonecs,
  SiAmazoneks,
  SiArgo,
  SiGithub,
  SiLinkedin,
  SiInstagram,
  SiX,
  SiFacebook,
};

export function getIconByName(name: string) {
  return ICON_MAP[name] || null;
}
